{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devops-assignment.fullname" . }}-prometheus-config
  namespace: {{ .Values.prometheus.namespace }}
  labels:
    {{- include "devops-assignment.prometheusLabels" . | nindent 4 }}
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.prometheus.scrapeInterval }}
      scrape_timeout: {{ .Values.prometheus.scrapeTimeout }}
      evaluation_interval: 30s
    
    scrape_configs:
      - job_name: 'devops-assignment'
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - {{ .Values.app.namespace }}
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: {{ include "devops-assignment.fullname" . }}
          - source_labels: [__meta_kubernetes_endpoint_port_name]
            action: keep
            regex: http
        metric_relabel_configs: []
{{- end }}
